### ISSUE TITLE
Unable to install using npm

### ISSUE THREAD

**Issue by Ashish2000L** [ashutosh1919/react-awesome-loaders#14]
I am using node 16.4.0

below are dependencies I am using to my project
```json
"dependencies": {
    "@hapi/joi": "^17.1.1",
    "bcryptjs": "^2.4.3",
    "cors": "^2.8.5",
    "crypto-js": "^4.1.1",
    "dotenv": "^16.0.1",
    "express": "^4.18.1",
    "jsonwebtoken": "^8.5.1",
    "mongoose": "^6.3.4",
    "sib-api-v3-sdk": "^8.3.0"
  }
```

```node
npm install git+https://github.com/ashutosh1919/react-awesome-loaders.git
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/schemas@28.0.2',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/console@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@jest/test-result@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: '@jest/types@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: 'jest-message-util@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: 'jest-regex-util@28.0.2',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: 'jest-util@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: 'jest-watcher@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {   
npm WARN EBADENGINE   package: 'pretty-format@28.1.0',
npm WARN EBADENGINE   required: { node: '^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0' },
npm WARN EBADENGINE   current: { node: 'v16.4.0', npm: '8.7.0' }
npm WARN EBADENGINE }
npm WARN deprecated @babel/preset-es2015@7.0.0-beta.53: 👋 We've deprecated any official yearly presets in 6.x in favor or babel-preset-env. For 7.x it would be @babel/preset-env.
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated  
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'      
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.  
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

Below is the error log after installation 
```node
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command C:\Program Files\nodejs\node.exe C:\Users\ashis\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js install --force --cache=C:\Users\ashis\AppData\Local\npm-cache --prefer-offline=false --prefer-online=false --offline=false --no-progress --no-save --no-audit --include=dev --include=peer --include=optional --no-package-lock-only --no-dry-run
npm ERR! npm WARN using --force Recommended protections disabled.
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN While resolving: @babel/preset-es2015@7.0.0-beta.53
npm ERR! npm WARN Found: @babel/core@7.18.0
npm ERR! npm WARN node_modules/@babel/core 
npm ERR! npm WARN   dev @babel/core@"^7.12.10" from the root project
npm ERR! npm WARN   7 more (@babel/plugin-proposal-class-properties, ...)
npm ERR! npm WARN
npm ERR! npm WARN Could not resolve dependency:
npm ERR! npm WARN peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/preset-es2015@7.0.0-beta.53
npm ERR! npm WARN node_modules/@babel/preset-es2015
npm ERR! npm WARN   @babel/preset-es2015@"^7.0.0-beta.53" from the root project       
npm ERR! npm WARN
npm ERR! npm WARN Conflicting peer dependency: @babel/core@7.0.0-beta.56
npm ERR! npm WARN node_modules/@babel/core 
npm ERR! npm WARN   peer @babel/core@">=7.0.0-beta.50 <7.0.0-rc.0" from @babel/preset-es2015@7.0.0-beta.53
npm ERR! npm WARN   node_modules/@babel/preset-es2015
npm ERR! npm WARN     @babel/preset-es2015@"^7.0.0-beta.53" from the root project     
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN ERESOLVE overriding peer dependency
npm ERR! npm WARN While resolving: babel-loader@7.1.5
npm ERR! npm WARN Found: babel-core@7.0.0-bridge.0
npm ERR! npm WARN node_modules/babel-core  
npm ERR! npm WARN   dev babel-core@"^7.0.0-bridge.0" from the root project
npm ERR! npm WARN
npm ERR! npm WARN Could not resolve dependency:
npm ERR! npm WARN peer babel-core@"6" from babel-loader@7.1.5
npm ERR! npm WARN node_modules/babel-loader
npm ERR! npm WARN   dev babel-loader@"^7.1.4" from the root project
npm ERR! npm WARN
npm ERR! npm WARN Conflicting peer dependency: babel-core@6.26.3
npm ERR! npm WARN node_modules/babel-core  
npm ERR! npm WARN   peer babel-core@"6" from babel-loader@7.1.5
npm ERR! npm WARN   node_modules/babel-loader
npm ERR! npm WARN     dev babel-loader@"^7.1.4" from the root project
npm ERR! npm WARN deprecated @babel/preset-es2015@7.0.0-beta.53: 👋 We've deprecated any official yearly presets in 6.x in favor or babel-preset-env. For 7.x it would be @babel/preset-env.
npm ERR! npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm ERR! npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm ERR! npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained       
npm ERR! npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm ERR! npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! npm WARN deprecated har-validator@5.1.5: this library is no longer supported 
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm ERR! npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm ERR! npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm ERR! npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm ERR! npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
npm ERR! npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm ERR! npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm ERR! npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm ERR! npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm ERR! npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142     
npm ERR! npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm ERR! npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm ERR! npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm ERR! npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-sass
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js  
npm ERR! npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=   
npm ERR! npm ERR! gyp info it worked if it ends with ok
npm ERR! npm ERR! gyp verb cli [
npm ERR! npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! npm ERR! gyp verb cli   'C:\\Users\\ashis\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-cloneTlhs2R\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! npm ERR! gyp verb cli   'rebuild',
npm ERR! npm ERR! gyp verb cli   '--verbose',
npm ERR! npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! npm ERR! gyp verb cli   '--libsass_library='
npm ERR! npm ERR! gyp verb cli ]
npm ERR! npm ERR! gyp info using node-gyp@3.8.0
npm ERR! npm ERR! gyp info using node@16.4.0 | win32 | x64
npm ERR! npm ERR! gyp verb command rebuild []
npm ERR! npm ERR! gyp verb command clean []
npm ERR! npm ERR! gyp verb clean removing "build" directory
npm ERR! npm ERR! gyp verb command configure []
npm ERR! npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! npm ERR! gyp verb `which` failed     at F (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! npm ERR! gyp verb `which` failed     at E (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\isexe\index.js:42:5
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\isexe\windows.js:36:5
npm ERR! npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21)
npm ERR! npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:13:12)
npm ERR! npm ERR! gyp verb `which` failed     at F (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:68:19)
npm ERR! npm ERR! gyp verb `which` failed     at E (C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:80:29)
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-gyp\node_modules\which\which.js:89:16
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\isexe\index.js:42:5
npm ERR! npm ERR! gyp verb `which` failed     at C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\isexe\windows.js:36:5
npm ERR! npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:195:21) {
npm ERR! npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! npm ERR! gyp verb `which` failed }
npm ERR! npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! npm ERR! gyp verb `which` succeeded python C:\Users\ashis\AppData\Local\Programs\Python\Python38\python.EXE
npm ERR! npm ERR! gyp ERR! configure error 
npm ERR! npm ERR! gyp ERR! stack Error: Command failed: C:\Users\ashis\AppData\Local\Programs\Python\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! npm ERR! gyp ERR! stack           
            ^
npm ERR! npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! npm ERR! gyp ERR! stack
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
npm ERR! npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)        
npm ERR! npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! npm ERR! gyp ERR! System Windows_NT 10.0.22000
npm ERR! npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\ashis\\AppData\\Local\\npm-cache\\_cacache\\tmp\\git-cloneTlhs2R\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="        
npm ERR! npm ERR! gyp ERR! cwd C:\Users\ashis\AppData\Local\npm-cache\_cacache\tmp\git-cloneTlhs2R\node_modules\node-sass        
npm ERR! npm ERR! gyp ERR! node -v v16.4.0 
npm ERR! npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! npm ERR! gyp ERR! not ok
npm ERR! npm ERR! Build failed with error code: 1
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\ashis\AppData\Local\npm-cache\_logs\2022-05-23T14_58_42_158Z-debug-0.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ashis\AppData\Local\npm-cache\_logs\2022-05-23T14_56_39_690Z-debug-0.log
```

**Comment by ashutosh1919** [comment]
@Ashish2000L please revise the versions of conflicting packages.
