### ISSUE TITLE
GYP ERR during installation

### ISSUE THREAD

**Issue by El-Potato-Slayer** [ashutosh1919/react-awesome-loaders#19]
Whenever I try to install the package, I get the following error:

```Building: C:\Program Files\nodejs\node.exe C:\Projects\project\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= 
--libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Projects\\project\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@16.13.2 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Projects\project\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\project\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\project\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\project\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\project\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\project\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Projects\project\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Projects\project\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Projects\project\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Projects\project\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Projects\project\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Projects\project\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:397:12)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at maybeClose (node:internal/child_process:1064:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
gyp ERR! System Windows_NT 10.0.19045
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\project\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Projects\project\node_modules\node-sass
gyp ERR! node -v v16.13.2
```

I've read the issue is related to not having python 2.7 installed, but wouldn't I be stuck with the same error if I eventually move to production unless I specifically have python 2.7 installed on the server?

**Comment by ashutosh1919** [comment]
@El-Potato-Slayer python is not installed in your system. Node requires python in backend. Closing this issue. Feel free to reopen if not solved.

**Comment by FlorianCassayre** [comment]
Why does it require Python 2 though? It's not installed anymore by default on Linux.

**Comment by ashutosh1919** [comment]
node uses python 2 internally.
